fhir/pom.xml, fhir/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java, fhir/src/main/java/org/techbd/service/api/http/fhir/FhirController.java
- Initialize ValidationOptions in the HapiValidationEngine constructor.
- Add FHIR profile URL to ValidationOptions if it's not null.
- Ensure validation checks for a non-null FHIR profile URL before proceeding.
- Return a specific ValidationResult when FHIR profile URL is null, with appropriate error messages.
- update application version to 0.50.1
=> feat: add validation option handling in HapiValidationEngine #1

hub-prime/pom.xml, hub-prime/src/main/java/org/inferno/validator/Validator.java, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java
- Add method to fetch FHIR profile version
- Improve performance by caching the FHIR profile version to reduce redundant network calls.
- Utilize HttpClient for asynchronous HTTP requests to fetch the FHIR profile version from the provided URL.
- Parse the JSON response using ObjectMapper to extract the "version" field.
- Ensure the method waits for the asynchronous operation to complete using join().
- remove fetching version from Validator class
- refactor code to enhances code readability and leverages Java's type inference for local variables.
=> feat: add methods for fetching FHIR profile version

hub-prime/src/test/java/org/techbd/service/http/hub/prime/ApplicationTests.java
Update JUnit test to use only the HAPI engine. 
Remove tests involving multiple engines.
=> fix: remove JUnit test issue found during cleanup

udi-prime/src/main/postgres/ingestion-center/001_idempotent_interaction.psql
This PR updates the SQL view for HTTP interactions to incorporate the header content introduced by the "Integrate reportable interaction timing metrics in UI/UX". Additionally, it adds a new view, 'interaction observe', to further enhance interaction observation and analysis.
- Modified the HTTP interactions SQL view to extract and utilize new header content from JSON payloads.
- Added a new view, 'interaction_observe', to facilitate enhanced observation of interactions.
=> feat:update sql view for http interactions to include new header content and add 'interaction_observe' view #108

hub-prime/src/main/java/org/techbd/service/http/Interactions.java, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java
Resolved the issue: after logging out from the application/GitHub, the user is able to access the site when directly accessing the interactions or diagnostics URL
=> feat: implement logout #135

udi-prime/src/main/postgres/ingestion-center/001_idempotent_interaction.psql
Summary:
Update the 'interaction_observe' view to remove and add fields for improved interaction observation and analysis.
Changes:
- Removed obsolete fields from 'interaction_observe' view.
- Added new fields for enhanced data representation.
=> feat: modify 'interaction_observe' view to update fields #108

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/DocsController.java, hub-prime/src/main/resources/templates/page/docs/schema.html, udi-prime/udictl.ts
- Added a new 'Schema' tab in the Documentation section of TechBD Hub.
- Enabled static browsing of SchemaSpy-generated documentation located in target/site/schemaSpy.
=> feat: Introduce SchemaSpy docs browser #102

hub-prime/pom.xml
Removed the following jars from pom.xml
spring-boot-starter-hateoas
duckdb_jdbc
spark-core
org.hl7.fhir.r4 6.3.6
org.hl7.fhir.utilities 6.3.6
org.json
snakeyaml
=> feat: Remove unused JARs and libs from pom.xml #82

hub-prime/pom.xml
fixed below vulnerabilities by upgrading com.vladsch.flexmark plugin
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-37714
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-36033
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27807
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-27906
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-31811
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-31812
=> feat: Resolve CVE reported by Red Hat #173

hub-prime/pom.xml
Resolved 
- Artifact relocation warning
[WARNING] The artifact org.hibernate:hibernate-core:jar:6.0.0.Final has been relocated to org.hibernate.orm:hibernate-core:jar:6.0.0.Final
- Commons Logging conflict warning:
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from class path in order to avoid potential conflicts
=> fix: resolve warnings while building the project  #215

hub-prime/pom.xml, hub-prime/src/main/resources/application.yml
update Data Lake API URL to https://qo5beg39c8.execute-api.us-east-1.amazonaws.com/dev/HRSNBundle
=> feat: update default Data Lake API URL  #307

hub-prime/src/main/resources/application.yml
updated the defaultDatalakeApiUrl to https://uzrlhp39e0.execute-api.us-east-1.amazonaws.com/dev/HRSNBundle in application.yml
=> feat: update defaultDatalakeApiUrl #463

hub-prime/src/test/java/lib/aide/JsonContentActionTest.java
- Updated `testRejectContentTransformation()` to replace `System.out.println` with assertions.
- Added assertions to verify `appliedJson` and `appendedJson` contents.
=> test: replace System.out.println with assertions in JsonContentActionTest #466

hub-prime/pom.xml, hub-prime/src/test/java/org/techbd/orchestrate/fhir/IgPublicationIssuesTest.java
- Temporarily disabled test functions in IgPublicationIssuesTest due to excessive heap memory usage, which was causing deployment issues.
=> test: comment out test functions in IgPublicationIssuesTest to prevent heap memory issues during deployment #732

hub-prime/pom.xml, hub-prime/src/test/java/org/techbd/orchestrate/fhir/IgPublicationIssuesTest.java
- Uncommented previously disabled code in IgPublicationIssuesTest.
- Updated to the latest Implementation Guide (IG) profile URL.
- Added UV-SDC packages to support extended validation capabilities.
- Implemented session clearing  after retrieving validation results to optimize memory usage.
=> test: uncomment IgPublicationIssuesTest code, update with latest IG profile URL, add UV-SDC packages, and clear validation session #732

support/specifications/ccda/NYHRSN-CCDA-examples/AHCHRSNScreeningResponseCCDExample.xml, support/specifications/ccda/NYHRSN-CCDA-examples/README.md, support/specifications/ccda/README.md
- Created a `ccda` folder with a subfolder `NYHRSN-CCDA-examples` for storing generated CCDA XML files.
- Added a README in the `ccda` directory outlining the steps and listing the files in the client-provided zip file.
=> docs: add CCDA folder with subfolder NYHRSN-CCDA-examples for generated CCDA files and include README with steps and file list #812

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CsvController.java
handle empty request and confirm extensions in CSV validate API
- Ensures empty requests are properly handled.
- Adds logic for confirming extensions during validation.
- Resolves issue #745.
=> fix: handle empty request and confirm extensions in CSV validate API

support/specifications/ccda/cda-fhir-bundle.xslt, support/specifications/ccda/cda-phi-filter.xslt
updated extension tag to include ssn number, mrn number and medicaid number.
Added condition to check the availability of data to display the tags.
Updated the structure of the patient resource.
=> docs: update patient resource in the xslt file with proper tags #947

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CsvController.java
-  implement file validation for bundle and validate endpoint #745
=> fix: implement validation for bundle and validate endpoint #745

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CsvController.java, hub-prime/src/main/java/org/techbd/service/CsvBundleProcessorService.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FHIRService.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/Hl7Service.java, hub-prime/src/test/java/org/techbd/service/CsvBundleProcessorServiceTest.java
- Removed fields:
* profile string (param)
* X-TechBD-FHIR-Profile-URI (header)
* HeaderName.Request.FHIR_VALIDATION_STRATEGY
* include-request-in-outcome
* include-operation-outcome
* include-incoming-payload-in-db
- Hidden fields:
* mtls-strategy
* immediate
* delete-session-cookie
* source of fhir bundle endpoint #745
=> chore: Remove and hide unnecessary FHIR endpoint configuration fields #745

support/specifications/ccda/cda-fhir-bundle.xslt
Updated the resource profile urls in the xslt file that is used for fhir bundle generation, to revert IG version from 1.3.0 to 1.2.3.
=> docs: update xslt file to revert IG version from 1.3.0 to 1.2.3 for profile urls #1162

support/specifications/ccda/cda-fhir-bundle.xslt
Update xslt file that is used for converting ccda xml file to fhir bundle so that the resource profile urls to be taken from the environment variables.
=> docs: update xslt file to revert IG version for profile urls using environment variables #1162

hub-prime/pom.xml, hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java
- Ensure that the AG Grid filter options 'Equals' and 'Does not equal' perform case-insensitive comparisons.
=> fix: make AG Grid 'Equals' and 'Does not equal' filters case insensitive #1201

hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java
- This PR addresses ticket #1201 by updating the AG Grid filtering logic to ensure that the 'Begins With' and 'Ends With' filters are case insensitive.
=> fix: Make AG Grid 'Begins With' and 'Ends With' filters case insensitive #1201

hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java, hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplierForSP.java
- This PR addresses ticket Correct the AG Grid filter issues in TechBD Hub #1201 by updating the AG Grid filtering logic to ensure that the 'Equals' and 'Does Not Equal' filters are case insensitive across all tabs. Additionally, it fixes the functionality of the 'Not Blank' filter
=> fix: make 'Equals' and 'Does Not Equal' filters case insensitive across all tabs and fix 'Not Blank' filter functionalit y in AG Grid #1201

hub-prime/src/main/java/org/techbd/model/csv/ScreeningProfileData.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/ConsentConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/EncounterConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/OrganizationConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java
- **EncounterConverter.java**: Updated `lastUpdated` to use `screeningProfileData.getEncounterStartDatetime()` instead of the current timestamp.
- **ConsentConverter.java**: Removed `CONSENT_POLICY_AUTHORITY` field from `ScreeningProfileData.java` and replaced it with a static UUID (`urn:uuid:d1eaac1a-22b7-4bb6-9c62-cc95d6fdf1a5`) in `populateConsentPolicy()`.
- Ensured consistency in encounter datetime handling and consent policy authority assignment.
=> refactor: Replace lastUpdated with encounterStartDatetime in EncounterConverter & set static consent policy authority #1181

hub-prime/src/main/java/org/techbd/service/converters/shinny/ProcedureConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java, hub-prime/src/main/resources/META-INF/additional-spring-configuration-metadata.json, hub-prime/src/main/resources/application.yml, hub-prime/src/test/java/org/techbd/service/csv/ProcedureConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/ScreeningResponseObservationConverterTest.java
- ProcedureConverter - Replaced custom meta creation with setMeta() call 
- ScreeningObservationConverter - Implemented common meta handling pattern 
- Updated related test cases to verify correct profile URLs
=> Fix: Implement common meta handling for FHIR resources (#1181)

hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java, hub-prime/src/test/resources/org/techbd/csv/generated-json/screening-response.json
- Changed `observationId` to use `data.getScreeningIdentifier()` instead of SHA-256 hashing
=> fix:  Updated Screening Identifier #1181

hub-prime/src/main/java/org/techbd/service/converters/shinny/PatientConverter.java, hub-prime/src/test/resources/org/techbd/csv/generated-json/patient.json
- Replaced hardcoded birth sex extension URL with value from demographicData
- Added display field for preferred language code in PatientConverter
- Updated patient.json test output to reflect changes
=> refactor: use dynamic extension URL and add display for preferred language #1181

hub-prime/src/main/java/org/techbd/service/converters/shinny/PatientConverter.java, hub-prime/src/test/resources/org/techbd/csv/generated-json/patient.json
- Changed birth sex extension URL back to "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex"
- Reverted dynamic assignment from demographicData.getSexAtBirthCodeSystem()
- Updated patient.json test output to reflect the change
=> fix: Revert to static birth sex extension URL in PatientConverter #1181

hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java
- The 'blank' and 'notBlank' filters work globally for all fields, including both date and string fields. 
- This ensures consistent behavior across the application and improves filter reliability.
=> fix: handle 'notBlank' and 'blank' filters correctly for 'request_time' field in AG Grid filters #1201

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/converters/shinny/BundleConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java
- Added performer reference to Observation using ORGANIZATION_ID in ScreeningResponseObservationConverter.java  
- Removed meta.setVersionId(igVersion) from BundleConverter.java to avoid setting versionId in generated Bundle
=> fix: add performer to Observation and remove versionId from Bundle meta #1322

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java
This update aligns the  version reference with the upgraded dependency in pom.xml.
=> fix: update  HAPI version to 8.0.0 in HapiValidationEngine #1348

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/CustomParserErrorHandler.java, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java
- Created CustomParserErrorHandler.java extending LenientErrorHandler
- Captures unknown elements and incorrect JSON types during parsing
- Issues are stored as OperationOutcome.Issue components for better diagnostics
- Integrated the custom handler into OrchestrationEngine
=> feat: add CustomParserErrorHandler to capture FHIR parse errors as OperationOutcome #1357

hub-prime/src/main/resources/application.yml, hub-prime/src/test/java/org/techbd/orchestrate/fhir/IgPublicationIssuesTest.java
- Reverted IG version from 1.4.5 back to 1.4.2 in `application.yml`.
- Updated the JUnit test file to reflect the correct IG version (1.4.2).
=> revert: rollback IG version to 1.4.2 in PROD #1425

hub-prime/pom.xml, hub-prime/src/main/resources/application-phiqa.yml, hub-prime/src/main/resources/application.yml, hub-prime/src/test/java/org/techbd/orchestrate/fhir/IgPublicationIssuesTest.java
- Re-applied IG version 1.4.5 to the test file after unintended rollback.
- Ensured both PROD and test environments consistently use version 1.4.5.
- Updated `baseFHIRURL` to http://shinny.org/us/ny/hrsn in application.yml and application-phiqa.yml.
- Cleaned up incorrect reversion from previous commit.
=> fix: restore IG version to 1.4.5 across all environments #1425

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/CustomParserErrorHandler.java
- Removed unused or redundant overridden methods from the custom error handler
- Retained essential parse error handling for better diagnostics and FHIR compliance
=> refactor: streamline CustomParserErrorHandler with necessary parse error overrides only #1357

hub-prime/src/test/java/org/techbd/service/csv/EncounterConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/OrganizationConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/PatientConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/ProcedureConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/ScreeningResponseObservationConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/SexualOrientationObservationConverterTest.java
- Injected mocks for UdiPrimeJpaConfig, CodeLookupService, and DSLContext
- Updated test files to use @Mock and @InjectMocks annotations
- Ensured test files are initialized with required mock dependencies
- Preserved test logic for verifying resource conversion and JSON output generation
=> test: update CSV conversion test files to use mocks and standardize setup #1467

hub-prime/src/test/java/org/techbd/service/csv/EncounterConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/OrganizationConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/PatientConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/ProcedureConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/ScreeningResponseObservationConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/SexualOrientationObservationConverterTest.java
- Removed `@Mock` annotation for DSLContext
- Cleaned up unused `org.mockito.Mock` import
=> test: remove unused @Mock annotation and DSLContext import from test files #1467

hub-prime/src/main/java/org/techbd/service/http/SwaggerConfig.java
- Update Swagger/OpenAPI to include both headers as required parameters for `/ccda/Bundle`
=> feat: map facility and encounter type from headers #1355

nexus-core-lib/src/main/java/org/techbd/service/csv/SimpleMultipartFile.java
- This utility class implements Spring's MultipartFile interface and is used in Mirth channels to wrap ZIP file bytes extracted from multipart/form-data HTTP requests. Enables seamless integration with CSV validation services.
=> feat: add SimpleMultipartFile class to wrap raw bytes as MultipartFile #1524

nexus-core-lib/src/main/resources/nexus-core-lib/application.yml
Replaced hardcoded script and data package paths with ${PYTHON_SCRIPT_PATH}.
=> fix: externalize flat file paths using env vars #1406

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter-medent.xslt
Added dataAbsentReason element to observation resource for unanswered screening question codes ("X-SDOH-FLO-1570000066-Patient unable to answer" and "X-SDOH-FLO-1570000066-Patient declined")
=> feat: add dataAbsentReason element to observation resource for unanswered screening question codes #1607

nexus-core-lib/src/main/java/org/techbd/config/Constants.java
- Updated BASE_FHIR_URL value from "X-TechBD-BASE_FHIR_URL" to "X-TechBD-Base-FHIR-URL" to match the correct header format. This fixes a casing issue introduced in a previous commit.
=> fix: correct header key for BASE_FHIR_URL #1406

support/specifications/develop/hl7/HL7V2 Bundle.xml
- Restricted Access-Control-Allow-Origin to https://hub.dev.techbd.org
- Updated Access-Control-Allow-Headers with required custom headers to resolve CORS issues
- Implemented request filtering in preprocessor to allow only POST requests to /hl7v2/Bundle or /hl7v2/Bundle/
- Prevented unwanted redirection by strictly validating contextPath and method
- Set responseMap 'status' for API success/failure tracking
- Updated UI to display dynamic response status using ${status}
=> feat: Add CORS support and request filtering in BridgeLink HL7v2 /Bundle channels #1695

integration-artifacts/hl7v2/hl7-techbd-channel-files/nexus/HL7V2 Bundle.xml
- Changed channel's data types to Raw to handle HL7v2 messages directly
- Stored original HL7v2 (ER7 format) payload in database
- Filtered only POST requests to /hl7v2/Bundle in preprocessor to prevent redirection
- Added response status tracking with responseMap and UI display via ${status}
- Applied CORS fix: allowed required headers and restricted origin to https://hub.dev.techbd.org
=> feat: support raw HL7v2 payload handling, validation, and CORS setup #1695

support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt, support/specifications/develop/ccda/cda-fhir-bundle-medent.xslt
Removed duplicate codes from multiple answers in component element of observation resource in fhir bundle for both Epic and Medent files.
Fixed issue with patient name when there are multiple patient elements in the ccda file.
=> fix: remove duplicate codes from multiple answers in component element of observation resource in fhir bundle #1714

nexus-core-lib/src/main/java/org/techbd/converters/csv/PatientConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/ScreeningResponseObservationConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/SexualOrientationObservationConverter.java
- Handled 'ASKU' & 'OTH' in SexAtBirthCode.
- Handled 'ASKU' & 'UNK' in Ethnicity.
- Handled 'ASKU' & 'asked-declined' in GenderIdentityCode.
- Handled 'ASKU' & 'UNK' in SexualOrientationCode.
- Handled 'NULL' in PotentialNeedIndicated.
=> fix: improve handling of demographic codes in converters #1690

support/specifications/develop/hl7/HL7V2 Bundle.xml
- Switched to SHA-256-based deterministic IDs for resources: patient, consent, organization, encounter, and observations.
- Introduced helper functions:
- generateSHA256Id: creates stable resource identifiers.
- getConsentResourceStatus: extracts and maps consent status from OBX segments.
- getPatientMRN: retrieves patient MRN from PID segment.
- getObservationCategoryCodes: derives observation categories from OBX segments and formats them for XSLT.
- Replaced UUID parameters in the transformer with SHA-256-generated IDs.
- Added support for grouper observation handling and observation category enhancement aligned with XSLT update.
- Improved observation formatting logic to support SDOH category classification and FHIR transformation.
=> feat: replace UUIDs with SHA-256-based resource IDs and add grouper observation handling #1695

nexus-ingestion-api/pom.xml, nexus-ingestion-api/src/main/java/org/techbd/ingest/controller/InteractionsFilter.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/feature/CheckFeature.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/feature/FeatureEnum.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/feature/TogglzConfiguration.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/listener/MllpRoute.java, nexus-ingestion-api/src/main/resources/application.yml
- Introduced new feature flag `DEBUG_LOG_REQUEST_HEADERS` using Togglz.
- Created `InteractionsFilter` to log HTTP request headers based on the flag.
- Integrated the same flag into the MLLP ingestion flow for consistent logging across protocols.
- Allows runtime toggle of request header logging via Togglz console or config without redeployment.
=> feat: add Togglz-based DEBUG_LOG_REQUEST_HEADERS flag for request header logging #1761

integration-artifacts/ccda/ccda-techbd-channel-files/mirth-connect/TechBD CCD Workflow.xml
Updated CCDA Mirth Connect channel file
- resolves issue with file name allowing special characters to the name part while checking the allowed extensions.
- fixed the error while sending through httpyac without setting the value for the header variable, X-TechBD-Base-FHIR-URL. If it is not set, the value from the environment variable Base-FHIR-URL will be taken.
- done checking the valid file extensions before checking the existence of ClinicaDocument tag in the input file
=> docs: update ccda channel xml file to integration-artifacts folder

hub-prime/pom.xml, nexus-core-lib/pom.xml, nexus-core-lib/src/main/java/org/techbd/service/fhir/FHIRService.java, pom.xml
- Ensures techByDesignDisposition is correctly set even if the `X-TechBD-HealthCheck` header is present but empty.
=> fix: handle missing techByDesignDisposition when `X-TechBD-HealthCheck` header is blank #1707

support/specifications/develop/ccda/CcdaBundleValidate.xml
- Fixed issue where records were wrongly inserted into sat_interaction_ccda_request table when CCDA validation fails
- Ensured 'Original CCDA Payload' nature is stored instead of 'Converted to FHIR' when validation fails
- Corrected From State column to display 'Validation Failed' instead of 'Validation Success' on failure cases
#1709
=> fix: align v0.7.0 with Synthetic v0.4.29 by correcting CCDA Bundle Validation handling #1709

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CsvController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java, nexus-core-lib/src/main/java/org/techbd/config/Constants.java, nexus-core-lib/src/main/java/org/techbd/service/csv/CsvBundleProcessorService.java, nexus-core-lib/src/main/java/org/techbd/service/fhir/FHIRService.java, nexus-core-lib/src/main/java/org/techbd/service/fhir/engine/OrchestrationEngine.java, nexus-core-lib/src/main/java/org/techbd/util/fhir/CoreFHIRUtil.java
This PR updates the TechBD validation APIs (/Bundle and /Bundle/$validate) to allow specifying a SHIN-NY IG version via the X-SHIN-NY-IG-Version header.
---
- Introduced `headerIgVersion` in OrchestrationEngine.validate() to track the requested IG version.
- Construct `shinNyPackagePath` dynamically depending on profile (test vs prod) and header value.
- Added CoreFHIRUtil.ensureEngineVersionMatches() to verify that the requested IG package exists and is valid.
- The validator uses the specified IG version to load the corresponding SHIN-NY IG for FHIR bundle validation.
- If the header is missing or invalid, the system defaults to the latest available SHIN-NY IG version.
- Logging updated for clarity on extracted profile URL, requested IG version, and resolved package path.
=> feat: add support for SHIN-NY IG version via header in Validation APIs #1791

nexus-core-lib/src/main/java/org/techbd/service/fhir/engine/OrchestrationEngine.java, pom.xml
- Added logic to derive `profileBaseUrl` from `profileUrl` by trimming
the `/StructureDefinition/...` suffix.
=> fix: extract base profile URL from StructureDefinition path #1791

integration-artifacts/ccda/ccda-techbd-channel-files/nexus/CcdaBundle.xml, integration-artifacts/version.json
- Fixed issue where 'Original CCDA Payload' was not displayed when CCDA validation fails
- Fixed issue where tenant_id and tenant_id_lower were displayed as 'undefined' on validation failure
#1709
=> fix: align v0.12.0 with Synthetic v0.4.30 by resolving CCDA bundle endpoint validation issues #1709

nexus-ingestion-api/src/main/resources/application.yml
- Changed default server port from 9999 to 8080 in application.yml
- Aligns with standard Spring Boot default port configuration
=> fix: standardize server port to 8080 in nexus-ingestion-api #1894

nexus-ingestion-api/src/main/resources/application.yml, pom.xml
- Update nexus-ingestion-api application.yml payload size limits from 10MB to 50MB:
* max-http-request-size: 10MB → 50MB
* max-swallow-size: 10MB → 50MB
* max-http-form-post-size: 10MB → 50MB
* max-file-size: 10MB → 50MB
* max-request-size: 10MB → 50MB
- Bump parent POM version from 0.682.0 to 0.683.0
#1894
=> feat: increase payload size limits and bump version to 0.683.0 #1894

nexus-core-lib/src/main/java/org/techbd/service/fhir/engine/OrchestrationEngine.java
- Reassigned `this.igVersion` after `validateAsRawPayload(...)` to prevent stale or incorrect values
- Fixes issue where multiple IG bundle validations in parallel caused wrong version to appear in OperationOutcome
=> fix: ensure correct IG version is set in OperationOutcome during parallel validations #1832

nexus-ingestion-api/src/main/java/org/techbd/ingest/service/MessageGroupService.java, nexus-ingestion-api/src/test/java/org/techbd/ingest/service/MessageProcessorServiceTest.java
- Introduced isDefaultTenantId() utility to identify placeholder tenant values.
- Updated message grouping logic to skip default tenant IDs.
- Implemented fallback to IP-based grouping when tenant ID is default or unknown.
- Changed final fallback value from DEFAULT_MESSAGE_GROUP to "unknown-tenantId".
- Added enhanced logging for tenant ID tracking and troubleshooting.
- Updated JUnit tests to cover new tenant ID logic.
=> fix: Refine tenant ID message grouping to exclude default values #1973

nexus-core-lib/src/main/java/org/techbd/converters/csv/BaseConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/OrganizationConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/PatientConverter.java, pom.xml
- Removed hardcoded "New York" → "NY" mapping logic.  
- Updated state resolution to follow a three-step lookup:
1. Attempt to resolve state using `fetchCode` (case-insensitive).  
2. If result equals the original value (not found in DB), attempt a new `fetchCodeFromDisplay` method.  
3. If no mapping exists, fall back to the original input.  
- Introduced `fetchCodeFromDisplay` method to resolve a code from a display value using DISPLAY_LOOKUP.  
- Ensured all lookups are case-insensitive to avoid issues with input variations.  
- This removes hardcoded state mappings and makes the logic fully data-driven via DB lookups.
=> fix: enhance state code handling in converters; added fetchCodeFromDisplay method for improved state resolution #1996

pom.xml, support/specifications/develop/flatfile-csv/FlatFileCsvBundleValidate.xml
- show validation error message when content type is missing or disabled in flat file CSV bundle validate endpoint.
-  bumped version to 0.723.0
=> fix: show validation error message when content type is missing or disabled in flat file CSV bundle validate endpoint #1708

udi-prime/src/main/postgres/ingestion-center/denormalize_data_integrity_errors.psql, udi-prime/src/main/postgres/ingestion-center/denormalize_errors.md, udi-prime/src/main/postgres/ingestion-center/denormalize_validation_errors.psql
- added denormalize_validation_errors.psql file to fill the 'file not processed' and 'incomplete groups' errors into `sat_csv_fhir_processing_errors` table.
- added denormalize_data_integrity_errors.psql file to fill the data_integrity errors into `sat_csv_fhir_processing_errors` table.
- added denormalize_errors.md file for the instructions to execute the psql files.
=> feat: create psql file to fill the validation errors for already ingested csv files #1912

udi-prime/src/main/postgres/ingestion-center/update_fhir_and_file_counts_in_zip_interaction_table.md, udi-prime/src/main/postgres/ingestion-center/update_fhir_count.psql
- added update_fhir_count.psql file to fill the `number_of_fhir_bundles_generated_from_zip_file` column into `sat_interaction_zip_file_request` table for showing the `FHIR count` in `CSV via HTTPs` page.
- added update_fhir_and_file_counts_in_zip_interaction_table.md file for the instructions to execute the psql files.
=> feat: update fhir count in zip file request table #1912

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt
Updated the following xslt files to fix issue in CCDA FHIR Bundles because of the nullFlavor in streetAddressLine element of address tag in Patient, Organization and Location resources.
=> fix: update xslt files to fix issue in CCDA FHIR Bundles because of the nullFlavor in streetAddressLine element of address tag #1367

nexus-ingestion-api/src/main/java/org/techbd/ingest/config/PortConfig.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/controller/DataHoldController.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/controller/DataIngestionController.java, nexus-ingestion-api/src/test/java/org/techbd/ingest/controller/DataHoldControllerTest.java, nexus-ingestion-api/src/test/java/org/techbd/ingest/controller/DataIngestionControllerTest.java, pom.xml
feat(nexus-ingestion-api): implement CR for `dataDir` and `metadataDir` in REST APIs #1864
- Update storage and metadata paths based on `portConfig` settings for /ingest
- Update storage and metadata paths based on `portConfig` settings for /hold
=> feat(nexus-ingestion-api): implement CR for `dataDir` and `metadataDir` in REST APIs #1864
