fhir/src/test/java/org/techbd/service/api/http/fhir/FhirEndpointsTests.java
- Update the `bundleValidateHealtheconnectionsUnhappyPath` test method.
- Include additional assertions to verify specific content in `OperationOutcome`.
- Ensure robust checking of device information and validation results.
- Resolve type safety warnings using `TypeReference` for JSON conversion.
=> test: improve unit tests for FHIR endpoint validation #1

fhir/src/main/java/org/techbd/sql/ArtifactsDataSource.java
implement `callStoredProcPersist` function with stored procedure call
=> feat: implement callStoredProcPersist function with stored procedure call #1

hub-prime/pom.xml, hub-prime/src/main/resources/application-devl.yml, hub-prime/src/main/resources/application-prod.yml, hub-prime/src/main/resources/application-stage.yml, hub-prime/src/main/resources/application.yml, hub-prime/src/test/java/org/techbd/service/http/hub/prime/ApplicationTests.java, hub-prime/src/test/java/org/techbd/util/ArtifactStoreTest.java
Changes
1. Changed the profile dynamic from environment variable
2. Added separate yml files for each profile (devl, stage, prod)
3. The changes in the pom.xml and test cases will be cleared up in the upcoming commit.
=> feat: changed the profile dynamic from environment variable

hub-prime/pom.xml
Updated the following Maven Plugins in the .pom file.
1. Formater
2. Spotbugs
3. git-commit-id
4. Modernizer
5. Enforcer
6. javadoc
=> Updated Maven Plugins in the POM file

hub-prime/src/main/resources/templates/layout/prime.html, hub-prime/src/main/resources/templates/page/home.html
Added User Profile Name
Added User Profile Image URL
=> Integrate User Profile picture in UI.

hub-prime/src/test/java/org/techbd/service/http/hub/prime/ApplicationTests.java
- Include tests to ensure proper handling of validation results for different engines.
- Validate that each validation engine performs as expected according to their respective validation results.
=> test: add unit tests for multiple validation engines #1

hub-prime/pom.xml
Added the following Maven Plugins in the .pom file:
1. Owasp
2. Jacoco
@raphaelvp @ratheesh-kr @razakpm Please review and merge, if it is fine.
=> Added Maven Plugins in the POM file - Owasp, Jacoco

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/AppConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/Controller.java, hub-prime/src/main/java/org/techbd/sql/ArtifactsDataSource.java, hub-prime/src/main/java/org/techbd/util/SessionWithState.java, hub-prime/src/main/resources/META-INF/additional-spring-configuration-metadata.json, hub-prime/src/main/resources/application.yml
`/Bundle` endpoint and related changes
=> feat: /Bundle endpoint and related changes

.envrc.example, hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java, hub-prime/src/main/java/org/techbd/service/http/filter/GitHubUserAuthorizationFilter.java, hub-prime/src/main/java/org/techbd/service/http/filter/GitHubUserService.java, hub-prime/src/main/java/org/techbd/service/http/filter/Users.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/Controller.java
New environment variable added for  YAML file in a private GitHub repository and token to access it.
- ORG_TECHBD_SERVICE_HTTP_FILTER_SENSITIVE_REPO_URL=https://api.github.com/repos/tech-by-design/infrastructure-prime/contents/sensitive/oauth2-github-authz.yml
- ORG_TECHBD_SERVICE_HTTP_FILTER_SENSITIVE_TOKEN=*********
=> integrate private github based allowed users #15

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/filter/GitHubUserAuthorizationFilter.java
Updated Error message with more user friendly message
=> chore: update error message #15

udi-prime/src/postgres/udi-ingestion-center-stored-routines.pgtap.psql, udi-prime/src/postgres/udi-ingestion-center-stored-routines.psql, udi-prime/src/postgres/udi-ingestion-center-views.psql, udi-prime/src/postgres/udi-ingestion-center.ts
Changes:
- Added new tables for UDI Data-Vault architecture.
- Implemented stored functions to support data processing within the vault.
- Created views for data retrieval and analysis.
=> feat: add udi data-vault objects including tables, stored functions and views

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/Controller.java, hub-prime/src/main/java/org/techbd/udi/InteractionRepository.java, hub-prime/src/main/java/org/techbd/udi/SessionIssueRepository.java, hub-prime/src/main/java/org/techbd/udi/entity/Interaction.java, hub-prime/src/main/java/org/techbd/udi/entity/SessionIssue.java, hub-prime/src/main/resources/templates/page/interactions/https.html
Changes:
1. Admin diagnostics data from the new data vault view
2. Interactions (HTTPS) tab data from the new data vault view
=> feat: load diagnostics data from view

udi-prime/udictl.ts
- Fix the issue related to SQL arguments that were preventing the execution of database migrations.
=> fix: issue with SQL arguments preventing database migrations

.envrc.example, hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/NoAuthSecurityConfig.java, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/Controller.java, hub-prime/src/main/resources/templates/layout/prime.html
Added a feature to work without authentication if the Spring profile is localopen.
Changed `Bundle/` to `Bundle` to avoid issues related to the trailing slash.
Implemented a temporary solution to handle errors related to content type mismatch and required header mismatch.
=> feat: disable login requirements in local environment #15

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/Controller.java
Added a fix to support both Bundle and Bundle/
=> fix: add support for trailing slash in Bundle api call #15

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java
Unprotected /error URI to fix showing the GitHub login page for unprotected URIs if an error occurs.
=> fix: unprotect /error uri #15

udi-prime/src/main/postgres/ingestion-center/mod.ts, udi-prime/src/main/postgres/ingestion-center/stored-routines.psql, udi-prime/src/main/postgres/ingestion-center/views-simple.sql, udi-prime/src/test/postgres/ingestion-center/stored-routines-unittest.psql, udi-prime/src/test/postgres/ingestion-center/suite.pgtap.psql
- Add a new stored function to handle interaction
- Modify the `interaction_http` view
- Include unit tests for the new stored function.
=> feat: add stored function for interaction, modify the view interaction_http #35

hub-prime/pom.xml, hub-prime/src/main/resources/templates/page/interactions/https.html
- Fixed issue with the request time format in the http ag grid interface.
=> Upgrade to version 0.76.0

udi-prime/src/main/postgres/ingestion-center/001_idempotent_interaction.psql, udi-prime/src/main/postgres/ingestion-center/mod.ts
Changed:
- Added field named `client_ip_address`.
- Added field named `user_agent`.
=> feat: include new fields to the interaction_http_request view object #35

hub-prime/pom.xml, hub-prime/src/main/resources/templates/page/interactions/orchctl.html
-Added orchctl page template for interactions page
=> Upgrade version to 0.78.0

udi-prime/src/main/postgres/ingestion-center/001_idempotent_interaction.psql
Sql view for sftp interactions
=> Sql view for sftp interactions

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/aggrid/SqlQueryBuilder.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/InteractionsController.java, hub-prime/src/main/java/org/techbd/udi/UdiPrimeJpaConfig.java, hub-prime/src/main/resources/templates/page/interactions/https.html
Changes:
Server-side pivoting for ag grid in http interaction page.
Java files are formatted and import organized.
Known issue: Pivoting with date column is not working.
=> feat: server-side pivoting for ag grid in http interaction page

.envrc.example, hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/GitHubUsersService.java, hub-prime/src/main/resources/logback-spring.xml
Added Log feature for Java application hub-prime
Added a fix to first login attempt white label error
=> White Label Error Page on First Login Attempt and log file #58, #59

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/InteractionsController.java, hub-prime/src/main/resources/templates/page/interactions/https.html, hub-prime/src/main/resources/templates/page/interactions/orchctl.html, hub-prime/src/main/resources/templates/page/interactions/sftp.html
- Fixed the date time display in sftp interaction grid.
=> upgrade version to  0.82.0

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/aggrid/ColumnFilter.java, hub-prime/src/main/java/org/techbd/service/http/aggrid/SqlQueryBuilder.java, hub-prime/src/main/java/org/techbd/service/http/aggrid/TextColumnFilter.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/InteractionsController.java
Screenshots:
Filtering with URI: ![1  Filtering with URI](https://github.com/tech-by-design/polyglot-prime/assets/110595249/00cb9ac7-1145-4dd0-a3dd-294ad4741cdc)
Pivoting after filtering: ![2  Pivoting after filtering](https://github.com/tech-by-design/polyglot-prime/assets/110595249/d6e4e39c-1ba3-4a01-b013-bec66a3fe077)
Grouping with URI: ![3  Grouping with URI](https://github.com/tech-by-design/polyglot-prime/assets/110595249/7aa9cc3c-af8e-48a6-b57a-f074395a481e)
=> feat: add server side filtering for AG Grid

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SwaggerConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/PrimeController.java, hub-prime/src/main/resources/templates/page/docs/announcements.html
- Added the tab announcements in the documentation.
- Updated fhirController with the proper Content-Type header.
=> feat: update documentation and fhirController #72

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java
Added redirection to savedRequest.getRedirectUrl() if savedRequest is not null
=> feat: Implement Post-Login Redirection to Initially Requested URL #73

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/PrimeController.java
login page will redirect to home page if a valid session is available
=> Post-Login Redirection to Initially Requested URL #73

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/DocsController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/MavenController.java, hub-prime/src/main/resources/templates/page/docs/project.html
updated project documentation tab to use local target/site location for consistent environment-specific docs
=> feat: update project documentation tab for consistent environment-specific docs #94

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/DynamicSqlQueryController.java, hub-prime/src/main/resources/templates/js/aggrid-aide.js, hub-prime/src/main/resources/templates/page/interactions/https.html, hub-prime/src/main/resources/templates/page/interactions/httpsfailed.html
Changes:
1. Introduced variable names for the schema and view names
2. Switch over the HTTP Failed tab page to AG Grid pages to use new AGGridAide
=> feat: aggrid-aide implementation in interaction pages #101

hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/DiagnosticsController.java
- Rename Diagnostics menu to Data Quality
- Create Flat File (CSV) Data Quality tab which would allow QEs to see their flat file content / data quality issues in CSVs
=> Introduce Data Quality UX #120

hub-prime/pom.xml
=> Update version to 0.108.0

udi-prime/src/main/postgres/ingestion-center/002_idempotent_diagnostics.psql
- Fix for the view that is to be displayed as data quality for CSV
=> Update the views for the data quality 

hub-prime/src/main/resources/templates/page/interactions/sftp.html
- updated sftp interaction failed count numbers.
=> Update sftp interaction failed count numbers 

hub-prime/src/main/resources/templates/page/interactions/sftp.html
- fixed sftp interaction failed count numbers popup .
=> fix for sftp interaction failed count numbers popup 

hub-prime/pom.xml
=> Update version to 0.111.0

hub-prime/src/main/java/org/techbd/service/http/GitHubUserAuthorizationFilter.java, hub-prime/src/main/java/org/techbd/service/http/NoAuthSecurityConfig.java
Resolved issue in the profile localopen
=> Resolve issue: Profile with localopen fails

hub-prime/pom.xml, hub-prime/src/main/resources/templates/fragments/nav.html
=> fix: footer nav links #116

udi-prime/src/main/postgres/ingestion-center/migrate-basic-infrastructure.ts, udi-prime/src/test/postgres/ingestion-center/fixtures.sql
-  udi initial migrations with islm.
=> feat: udi initial migrations with ISLM  #35

hub-prime/pom.xml
=> Update to version 0.120.0

hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/PrimeController.java, hub-prime/src/main/resources/templates/page/home.html
The changes include:
- Implementation of the REST endpoint.
- JOOQ integration for database views.
=> feat: add most recent FHIR interactions widget in home page #178

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/PrimeController.java
- add the most interaction count in FHIR interactions widget in home page
- update version to 0.124.0
=> add most interaction count in FHIR interactions widget in home page and update version to 0.124.0  #178

hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java, hub-prime/src/main/java/org/techbd/orchestrate/sftp/SftpAccountsOrchctlConfig.java, hub-prime/src/main/java/org/techbd/orchestrate/sftp/SftpManager.java, hub-prime/src/main/java/org/techbd/service/http/GitHubUserAuthorizationFilter.java, hub-prime/src/main/java/org/techbd/service/http/InteractionsFilter.java, hub-prime/src/main/java/org/techbd/util/ArtifactStore.java, hub-prime/src/main/java/org/techbd/util/JsonText.java
Resolved the below Spotbug issues
MS_SHOULD_BE_FINAL
EI_EXPOSE_REP2
NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
DM_DEFAULT_ENCODING
=> chore: resolve issues reported by spotbugs #190

hub-prime/pom.xml, hub-prime/src/main/resources/templates/page/diagnostics/sftp-rejected.html, hub-prime/src/main/resources/templates/page/diagnostics/sftp.html, udi-prime/src/main/postgres/ingestion-center/migrations/migrate-basic-infrastructure.ts, udi-prime/src/main/postgres/ingestion-center/migrations/migrate-diagnostics-fhir-view.ts, udi-prime/src/main/postgres/ingestion-center/migrations/migrate-interaction-fhir-view.ts, udi-prime/src/main/postgres/ingestion-center/migrations/migrations.ts, udi-prime/udictl.ts
- improve data quality UI in SFTP rejection grid
- ISLM migration updates
=> improve data quality UI in SFTP rejection grid

hub-prime/pom.xml, hub-prime/src/test/java/archunit/CyclicDependencyArchRulesTest.java, hub-prime/src/test/java/archunit/GeneralArchRulesTest.java, hub-prime/src/test/java/archunit/InterfaceArchRulesTest.java, hub-prime/src/test/java/archunit/NamingArchRulesTest.java
Changes:
pom.xml and 4 new test class files
=> feat: add archunit and test cases #161

hub-prime/src/main/java/lib/aide/resource/collection/PathElaboration.java, hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java, hub-prime/src/main/java/lib/aide/tabular/TabularRowsRequest.java, hub-prime/src/main/java/org/techbd/service/DocResourcesService.java, hub-prime/src/main/java/org/techbd/service/http/GitHubUsersService.java, hub-prime/src/main/java/org/techbd/util/NoOpUtils.java
Resolved issues reported through PMD Source code Analyzer in https://synthetic.fhir.api.devl.techbd.org/docs/project
https://docs.pmd-code.org/pmd-doc-7.0.0/pmd_rules_java_bestpractices.html
UnnecessaryModifier
EmptyCatchBlock
CollapsibleIfStatements
SimplifiedTernary
etc...
=> chore: resolve issues reported by PMD Analyzer #217

hub-prime/pom.xml, hub-prime/src/main/resources/templates/js/fhir-view.js
fix: correct data retrieval in observation section
=> chore: update to version 0.134.0

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/ContentController.java, hub-prime/src/main/resources/templates/js/aggrid-aide.js, hub-prime/src/main/resources/templates/page/content/patients.html
Changes:
1. New function in controller
2. New HTML file for patients listing and details page
3. Update in the JS file for master/detail view in AGGrid
4. Version update in pom.xml
=> feat: patients tab listing and details #205

hub-prime/src/main/java/lib/aide/paths/Paths.java, hub-prime/src/main/java/lib/aide/resource/nature/FrontmatterNature.java, hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java, hub-prime/src/main/java/org/techbd/conf/Configuration.java, hub-prime/src/main/java/org/techbd/orchestrate/sftp/SftpAccountsOrchctlConfig.java, hub-prime/src/main/java/org/techbd/orchestrate/sftp/SftpManager.java
Resolved check style issues reported as 
METHOD_DEF
ModifierOrder
NeedBraces
=> Resolve issues reported by CheckStyle Static Code Analysis Tool #242

hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/ExpectController.java
- Added /api/expect/fhir/bundle endpoint to register FHIR Bundle expectations, storing them in the HTTP interaction table for future queries.
=> feat: add API endpoints for FHIR Bundle expectation registration  #240

hub-prime/src/main/java/org/techbd/orchestrate/sftp/SftpManager.java, hub-prime/src/main/java/org/techbd/service/DocResourcesService.java, hub-prime/src/main/java/org/techbd/service/http/SandboxHelpers.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/AppConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/route/RoutesTree.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/TabularRowsController.java, hub-prime/src/main/java/org/techbd/util/ArtifactStore.java
Resolved the below issues 
NeedBraces
OverloadMethodsDeclarationOrder
EmptyLineSeparator
ModifierOrder
CommentsIndentation
=> Resolved issues reported by CheckStyle #242

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/InteractionsFilter.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/ExpectController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/route/RoutesTrees.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/ContentController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/DataQualityController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/InteractionsController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/PrimeController.java, hub-prime/src/main/java/org/techbd/udi/UdiPrimeJpaConfig.java, hub-prime/src/main/java/org/techbd/util/ArtifactStore.java
Resolve SpotBugs Bug Detector Report #190 
- resolved URF_UNREAD_FIELD
Resolve issues reported by PMD #217 
- resolved UnusedPrivateMethod
- resolved UnusedFormalParameter
- resolved UnusedLocalVariable
Resolve issues reported by CheckStyle #242
- resolved AbbreviationAsWordInName
=> chore: resolve spotbug, pmd and checkstyle issues

hub-prime/src/main/resources/templates/page/content/patients.html
- Automatically load questions and answers if there is only one screening info under a patient
- Require user to click on screening info to view questions and answers if there are multiple screening info entries
=> feat: auto-load questions/answers for single screening info, click required for multiple #205

hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/ContentController.java, hub-prime/src/main/resources/templates/js/aggrid-aide.js, hub-prime/src/main/resources/templates/page/content/organizations.html, hub-prime/src/main/resources/templates/page/content/patients.html
- Organizations grid with subgrid displaying patients
- Patients subgrid with further subgrid displaying screenings
- Screenings subgrid showing questions and answers
=> feat: enabled the tab Organizations with nested subgrids #205

hub-prime/src/main/java/org/techbd/conf/Configuration.java, hub-prime/src/main/java/org/techbd/service/http/Interactions.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/AppConfig.java
Resolved SIC_INNER_SHOULD_BE_STATIC
This class is an inner class, but does not use its embedded reference to the object which created it.  This reference makes the instances of the class larger, and may keep the reference to the creator object alive longer than necessary.  
verified the class has only static fields or static methods
=> chore: resolve spot-bugs issues #190

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java
- Integrated ValidationSupportChain to enhance the modularity and flexibility of FHIR resource validation.
- Added  validation support modules, including DefaultProfileValidationSupport  and PrePopulatedValidationSupport.
=> feat: implement Flexible FHIR Validation with ValidationSupportChain #312

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/GitHubUserAuthorizationFilter.java, hub-prime/src/main/java/org/techbd/service/http/GitHubUsersService.java
Configured Spring Security to ensure that access to Actuator endpoints is restricted to users with the ADMIN role and actuator resource access.
=> feat: restrict actuator API Access #343

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/TabularRowsController.java, hub-prime/src/main/resources/templates/page/diagnostics/ig-publication-issues.html
=> fix change the date format issue and update date order desc #350

hub-prime/src/main/resources/templates/page/interactions/httpsfailed.html
=> fix: change to new view name add download button in fhir failed listing page #141

hub-prime/pom.xml, hub-prime/src/main/resources/templates/fragments/nav.html
=> fix: hide need attention menu from the top navigation #239

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/InteractionsFilter.java, hub-prime/src/main/resources/META-INF/additional-spring-configuration-metadata.json, hub-prime/src/main/resources/application-sandbox.yml, hub-prime/src/main/resources/application.yml
Add option to enable or disable storage of user details for interactions #386
=> feat: add option to enable or disable storage of user details for interactions #386

.envrc.example, hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/InteractionsFilter.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/AppConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/health/BundleHealthIndicator.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/health/BundleValidateHealthIndicator.java
health check endpoints for APIs #467
=> feat: health check endpoints for APIs #467

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FHIRService.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java
=> fix : Add clear methods to remove object references after each request #688

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SwaggerConfig.java
=> fix: remove generated server from the server dropdown of the swagger ui #656

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FhirController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/GlobalExceptionHandler.java
=> fix : add null check and add additional details in log for internal server error#360

hub-prime/src/main/java/org/techbd/orchestrate/csv/CsvOrchestrationEngine.java
- validate and submit flat file (CSV) bundles for the latest four single screening files.
=> feat: validate and submit flat file (CSV) bundles for the latest four screening files #745

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java, hub-prime/src/main/java/org/techbd/service/http/SwaggerConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/GlobalExceptionHandler.java
Changes:
1. fix: change invalid header name to proper header name
2. fix: add swagger documentation for flatfile csv API endpoint #892
3. revert: revert the changes of v0.383.0
=> fix: swagger documentation for flatfile CSV API endpoint, fix improper header name

hub-prime/src/main/java/org/techbd/service/converters/shinny/ConsentConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/EncounterConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/SexualOrientationObservationConverter.java
- Comment out narrative text in SexualOrientationObservationConv erter, ConsentConverter, and EncounterConverter #745
=> fix: Comment out narrative text in SexualOrientationObservationConv erter, ConsentConverter, and EncounterConverter #745

support/specifications/ccda/cda-fhir-bundle.xslt
Update xslt file for fhir bundle generation to remove empty tags #947
=> docs: update xslt file for fhir bundle generation to remove empty tags #947

support/specifications/ccda/cda-fhir-bundle.xslt, support/specifications/ccda/cda-phi-filter.xslt
Update cda-phi-filter.xslt file to extract additional tags of consent and observation resources to the xml file.
Update cda-fhir-bundle.xslt file to add additional elements to consent and observation bundle resources.
=> docs: update xslt files to generate consent and observation bundle resources #947

support/specifications/ccda/cda-fhir-bundle.xslt, support/specifications/ccda/cda-phi-filter.xslt
Updated address and telecom in the Organization resource.
Updated subject in the Observation and Encounter resource.
Updated the observation resource id generation.
=> docs: update xslt file to modify the organization and encounter resources #947

hub-prime/pom.xml, udi-prime/src/main/postgres/ingestion-center/001_idempotent_interaction.psql
[fix: issue count for interactions](https://github.com/alan-francis/polyglot-prime/commit/1befab7e579e00795dc8a48ddd64f8bd7269ec53)
[feat: update insertion for multiple fields in diagnostics satellite table](https://github.com/alan-francis/polyglot-prime/commit/c9d55525ab1eaedabca1fde6ae2acdfe6f117bb5) https://github.com/tech-by-design/polyglot-prime/issues/1057
=> update to version 0.439.0

support/specifications/ccda/cda-fhir-bundle.xslt
Add new resource for Sexual orientation Observation.
Update Bundle, Patient and Observation resources to correct the date time formats, value codable concepts and profile urls.
=> docs: update xslt file with sexual orientation observation resource #947

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CsvController.java, hub-prime/src/main/java/org/techbd/service/CsvBundleProcessorService.java, hub-prime/src/main/java/org/techbd/service/CsvService.java, hub-prime/src/test/java/org/techbd/service/CsvBundleProcessorServiceTest.java
…for csv /flatfile/csv/Bundle endpoint
=> feat: add parameter append-validation-issue with default true for csv/flatfile/csv/Bundle endpoint

hub-prime/pom.xml, udi-prime/src/main/postgres/ingestion-center/001_idempotent_interaction.psql
[fix: missing validation issues](https://github.com/tech-by-design/polyglot-prime/commit/13222f98d14c5e1ca9960f724673c1e44c40fc8e) https://github.com/tech-by-design/polyglot-prime/issues/1073
=> update version to 0.442.0

hub-prime/pom.xml, udi-prime/src/main/postgres/ingestion-center/migrations/migrate-basic-infrastructure.ts
[feat: create index on the ccda satellite tables with idempotent statements https://github.com/tech-by-design/polyglot-prime/issues/1011](https://github.com/tech-by-design/polyglot-prime/commit/064173236d05e403814dec8e84fc81604f4f110f)
=> version update to 0.443.0

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CsvController.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/GlobalExceptionHandler.java
- implement fix for multipart exception for CSV bundle and validate endpoint #745
=> fix: implement fix for multipart exception for CSV bundle and validate endpoint #745

hub-prime/src/test/java/org/techbd/FileProcessorTest.java, hub-prime/src/test/java/org/techbd/service/csv/ScreeningResponseObservationConverterTest.java, hub-prime/src/test/java/org/techbd/service/csv/SexualOrientationObservationConverterTest.java
- fix test cases for SexualOrientationObservationConverterTest, ScreeningResponseObservationConverterTest, and FileProcessorTest #745
=> test: fix test cases for SexualOrientationObservationConverterTest, ScreeningResponseObservationConverterTest, and FileProcessorTest #745

hub-prime/src/test/java/org/techbd/service/CsvServiceTest.java
-  test: implement j-unit tests for CsvService #745
=>  test: implement junit tests for CsvService #745

hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/FHIRService.java
…instead of parsing to r4 Bundle object   #1118
=> feat: modify bundle profile url validation by extracting profile url instead of parsing to r4 Bundle object #1118

support/specifications/ccda/cda-fhir-bundle.xslt, support/specifications/ccda/cda-phi-filter.xslt
Updated cda-phi-filter.xslt to filter the questionnaire data from the ccda xml file.
Updated cda-fhir-bundle.xslt file to add questionnaire and questionnaireresponse resources to fhir bundle.
=> docs: update xslt files to add questionnaire and questionnaireresponse resources to fhir bundle #1177

support/specifications/ccda/cda-fhir-bundle-epic.xslt, support/specifications/ccda/cda-phi-filter-epic.xslt
Created XSLT files for filtering CCD XML files and generating FHIR bundles for Epic CCD XML files.
Encounter resource in the fhir bundle has been updated with additional tags.
=> docs: create XSLT files for filtering and generating FHIR bundles for Epic CCD XML files #1155

support/specifications/ccda/cda-fhir-bundle.xslt, support/specifications/ccda/cda-phi-filter.xslt
Updated FHIR bundle encounter resource with additional tags for ccd xml files.
Updated phi filter xslt file to include all the tags from the xml file for the selected resources and updated the bundle generation xslt file accordingly.
=> docs: update fhir bundle encounter resource with additional tags for ccd xml files #1177

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/util/CsvConversionUtil.java, hub-prime/src/main/resources/application.yml
Fixed CSV processing error by removing UTF-8 BOM from the first line, allowing correct parsing without unexpected characters
=>  fix: Fixed CSV processing error by removing UTF-8 BOM from the first line, allowing correct parsing without unexpected characters#1189

hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java
- resolve issue when selecting blank and not blank filter options in the grid
=> fix: resolve issue when selecting blank and not blank filter options in the grid #1186

support/specifications/ccda/cda-fhir-bundle-epic.xslt, support/specifications/ccda/cda-fhir-bundle.xslt, support/specifications/ccda/cda-phi-filter-epic.xslt, support/specifications/ccda/cda-phi-filter.xslt
Update all the resources to handle Null Flavor, multiple addresses and telecoms and format all the date time values.
Updated Patient - communication - language, gender, address, extension - race and ethnicity, telecom and name.
Organization - telecom, address and formatting date time.
Encounter - formatting date time.
SexualOrientation - effectiveDateTime.
Observation - status.
=> docs: update resources to handle null flavor, multiple addresses and telecoms and format date time #1177

support/specifications/ccda/cda-fhir-bundle-epic.xslt, support/specifications/ccda/cda-phi-filter-epic.xslt
Update XSLT file for generating FHIR bundle from Epic CCDA XML file to convert CCDA codes to corresponding FHIR codes.
Update the following:
Patient - gender, telecom, address 
Observation - status
SexualOrientation - status
Organization - address 
Consent - Status
=> docs: update xslt file to convert ccda codes to corresponding fhir codes #1155

support/specifications/ccda/cda-fhir-bundle-epic.xslt, support/specifications/ccda/cda-fhir-bundle.xslt
Update xslt file to change the status of questionnaire response resource to 'completed'
=> docs: update xslt file to change status of questionnaireresponse resource #1208

support/specifications/ccda/cda-fhir-bundle-epic.xslt, support/specifications/ccda/cda-fhir-bundle.xslt
Update xslt file to change profile url generation by combining base url and the resource url.
=> update xslt file to change profile url generation

hub-prime/src/main/java/org/techbd/model/csv/ScreeningProfileData.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/ConsentConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/OrganizationConverter.java, hub-prime/src/main/java/org/techbd/service/converters/shinny/PatientConverter.java, hub-prime/src/test/resources/org/techbd/csv/generated-json/consent.json, hub-prime/src/test/resources/org/techbd/csv/generated-json/organization.json
- Added new fields to ScreeningProfileData model.
- Updated ConsentConverter to populate policy.authority from ScreeningProfileData.
- Set meta.lastUpdated using ConsentDateTime instead of a static value.
- Improved handling of race and ethnicity descriptions in PatientConverter.java to prevent errors and ensure consistency.
- Regenerated consent.json to reflect recent changes.
=> feat: Enhance ScreeningProfileData and Consent conversion logic #1181

hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java
Replaced static language value with dynamic screeningLanguageCode from screeningProfileData in ScreeningResponseObservationConverter.java
=> refactor: replace static language value with dynamic value

hub-prime/src/main/java/org/techbd/service/converters/shinny/PatientConverter.java, hub-prime/src/test/java/org/techbd/service/csv/PatientConverterTest.java
- resolve format issue  with race and ethnicity in generated FHIR json
=> fix: resolve format issue  with race and ethnicity in generated FHIR json #1181

hub-prime/src/main/java/org/techbd/service/converters/shinny/ProcedureConverter.java, hub-prime/src/test/java/org/techbd/service/csv/ProcedureConverterTest.java
- Removed DEFAULT_SYSTEM and DEFAULT_PROCEDURE_DISPLAY constants
- Updated procedure coding to use values directly from profileData
- Eliminated fallback defaults for procedure code system and description
- Updated ProcedureConverterTest to mock procedure code system in unit tests
=> refactor: remove static defaults for procedure system and display, update unit test #1181

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Updated Consent -> scope, category, sourceAttachment, datetime and policy.
Patient -> identifier - system. Removed SSN.
Removed meta and questionnaire link from questionnaireResponse Resource.
=> docs: fix issues with consent and patient resources #1233

hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java
- Fixed filtering logic for 'before', 'after', 'equals', 'not equals', 'blank', and 'not blank' conditions in request-time filters.
=> fix: resolve request-time filtering issues without combinations in AG grid #1201

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Updated patient -> ethnicity - restricted display.
Updated Observation -> removed category.
Updated questionnaireresponse  -> item and answer - system to "http://loinc.org"
=> docs: update patient, observation and questionnaireresponse resources  #1233

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
1. Add zone to all date time fields, updated the following:
-meta.lastUpdated in all the resources
-consent.datetime
-patient.name.period
-patient.address.period
-encounter.period 
2. Observation -> category - removed categories from the ccda xml those are not getting validated
3. Observation -> effective time - if not available show the current time
=> docs: update xslt files to validate fhir bundle generated from CCDA xml file #1233

hub-prime/pom.xml, hub-prime/src/main/java/lib/aide/tabular/JooqRowsSupplier.java
- resolve numeric type issue and equality check for AG grid filters.
- Updated the version to 504.
=> fix: resolve numeric type issue and equality check for AG grid filters #1201.

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java
=> fix: update performer reference for grouper observation #1277

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter.xslt
Add performer reference to all observation resources.
Add encounter resource from component.structuredBody.entry.
=> docs: update observation and encounter resources for CCDA xml file #1233

hub-prime/pom.xml
…olve vulnerability reported #177
=> feat(dependencies): add commons-vfs2 dependency version 2.10.0 to resolve vulnerability reported #177

support/specifications/ccda/ccda-techbd-schema-files/POCD_MT000040.xsd
Updates POCD_MT000040.xsd file by adding extensions for functionCode, raceCode and ethnicGroupCode from the SDTC namespace.
=> docs: update xsd file to add SDTC namespace extensions for validating ccda files #1315

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java
…in ScreeningResponseObservationConverter #1277
=> chore: update version to 0.510.0 and comment out performer reference in ScreeningResponseObservationConverter #1277

hub-prime/pom.xml, hub-prime/src/test/java/org/techbd/orchestrate/fhir/OrchestrationEngineTest.java
=> test: temporarily disable IG package loading tests to investigate Java heap memory issue #1351

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Update patient resource in the xslt file to correct the position of request entry.
=> docs: update patient resource in the  xslt file to correct the position of request entry

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter-medent.xslt
updated xslt files to exclude sections irrelevant to FHIR bundle generation #1355
updated communication json format in patient  resource 
updated xslt files to exclude sections irrelevant to FHIR bundle generation
removed questionnaire and questionnaire resources
=> fix: update xslt files to exclude sections irrelevant to FHIR bundle generation #1355

hub-prime/pom.xml, hub-prime/src/main/resources/application-stage.yml
- Added dataLedgerApiUrl and dataLedgerDiagnostics, enable(true) dataLedgerTracking in application-stage.yml
=> feat: configure DataLedger settings in application-stage.yml #1213

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
updated xslt files to fix issue with consent resource provision type
=> docs: update xslt files to fix issue with consent resource #1355

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-phi-filter.xslt
updated xslt files to filter irrelevant data from ccda files other than epic or medent.
update marital status code for unknown codes.
=> docs: update xslt files to filter irrelevant data from ccda files other than epic or medent #1355

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java
=> feat: enable concurrent bundle validation with custom executor in FhirValidator #1401

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Updated xslt files to implement SDOH Category codes in Observation resources.
Update xslt files to fix issues with MaritalStatusCode, BirthSex, Questionnaire Resource and Identifier.
=> feat: update xslt files to implement SDOH Category codes in Observation resources #1355

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Update xslt files to fix FHIR bundle validation issues with MaritalStatusCode, system and Identifier in bundle Resources.
Update xslt files to implement the CIN, MRN and SSN identifiers with rules in patient resource.
=> feat: update xslt files to implement the CIN, MRN and SSN identifiers with rules in patient resource #1355

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/OrchestrationEngine.java
Added fix for certain bundle rules not getting validated when concurrency is enabled
=> feat: enable validation and set bundle profile URL in ValidatorOptions #1401

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/orchestrate/fhir/CustomParserErrorHandler.java
- Added support for handling unknown attributes, unexpected repeating elements, and unknown references
- Implemented handling for extensions with both value and nested extensions
- Captures invalid values, missing required elements, and contained resources without IDs
- All issues are stored as OperationOutcome.Issue components for consistent error reporting
- Improves overall diagnostic coverage for FHIR resource parsing
=> feat: enhance CustomParserErrorHandler with additional FHIR parse error handling #1357

hub-prime/src/test/java/org/techbd/orchestrate/fhir/IgPublicationIssuesTest.java
…issues with severity error in operation outcome #1351
=> test: fix name in sure fire report and modify to fail if there are any errors in operation outcome #1351

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Updated encounter 
- mapped status code from ccda to corresponding fhir encounter status code.
- added full list of participant type from https://terminology.hl7.org/6.3.0/CodeSystem-v3-ParticipationType.html
- updated encounter type system.
=> docs: update xslt files to fix issues with encounter resource in CCDA files #1355

hub-prime/pom.xml, pom.xml
Added <maven.compiler.parameters>true</maven.compiler.parameters> in pom.xml
to include method parameter names in the compiled class files.
=> chore: enable compiler parameter names

hub-prime/src/main/java/org/techbd/service/converters/shinny/ScreeningResponseObservationConverter.java, pom.xml
- Implemented IG v1.5.0 requirement to capture answers to questionCode 96778-6 under Observation.component
- Ensures multiple housing-related issues are properly recorded as component entries
- Applies only to questionCode 96778-6; other codes continue to use valueCodeableConcept
=> feat: support IG v1.5.0 rule for housing question 96778-6 in Observation component #1467

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt
Updated patient resource identifier element, new logic for MRN, CIN and SSN, for epic ccda files
=> fix: update patient resource identifier element for epic ccda files #1355

hub-prime/pom.xml
=> chore(maven): prioritize local .m2 repository to avoid redundant downloads #1406

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Updated xslt files to change 
1. Observation effectiveDateTime, 
2. MRN facility code, 
3. Encounter type code,
4. Sexual orientation valueCodeableConcept system
=> fix: update xslt files to change observation effectiveDateTime, MRN facility code, encounter type and sexual orientation valueCodeableConcept #1355

hub-prime/src/main/resources/application-phiqa.yml
- updated baseFHIRURL to PROD SHIN-NY IG url  in application-phiqa.yml
=> fix: update baseFHIRURL to PROD SHIN-NY IG url  in application-phiqa.yml #1552

hub-prime/pom.xml, nexus-core-lib/pom.xml, nexus-core-lib/src/main/java/org/techbd/config/Nature.java, pom.xml
- correct FHIR payload description casing #1524
=> fix: correct FHIR payload description casing #1524

nexus-core-lib/src/main/java/org/techbd/service/csv/CsvBundleProcessorService.java
- enable X-TechBD-Validation-Severity-Level from request param eters for CSV validation #1524
=> fix: enable X-TechBD-Validation-Severity-Level from request param eters for CSV validation #1524

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt
Added grouper observation resource to add the hasMember element in CCDA FHIR bundle for both Epic and Medent files
=> feat: add grouper observation resource to add the hasMember element in CCDA FHIR bundle #1608

support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt
Update screening code selection code for Medent CCD files
=> fix: improve screening code handling in XSLT for Medent ccd files #1608

support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt, support/specifications/develop/ccda/cda-fhir-bundle-medent.xslt, support/specifications/develop/ccda/cda-fhir-bundle.xslt, support/specifications/develop/ccda/cda-phi-filter-epic.xslt, support/specifications/develop/ccda/cda-phi-filter-medent.xslt, support/specifications/develop/ccda/cda-phi-filter.xslt, support/specifications/develop/hl7/hl7v2-fhir-bundle.xslt
Created new folder structure for keeping development xslt files for both ccda and hl7.
Resolved issue with duplicate observation codes.
=> fix: resolve issue with duplicate observation codes #1608

support/specifications/develop/hl7/hl7v2-fhir-bundle.xslt
Relationship and participant type changes according to the updated spec.
=> fix: enhance relationship and participant type handling in HL7 mapping #1494

hub-prime/pom.xml, hub-prime/src/main/java/org/techbd/service/http/hub/prime/api/GlobalExceptionHandler.java, hub-prime/src/main/resources/application.yml, nexus-core-lib/pom.xml, pom.xml
=> feat :Improve error handling for multipart upload failures with detaled messages #1651

support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt, support/specifications/develop/ccda/cda-fhir-bundle-medent.xslt
Updated data absent reason handling for specific observation codes
=> fix: update data absent reason handling for specific observation codes in XSLT files #1673

nexus-core-lib/src/main/java/org/techbd/converters/csv/EncounterConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/PatientConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/SexualOrientationObservationConverter.java
- update display fetching for coding in Encounter, Patient, and `SexualOrientationObservation` converters #1690
=> fix: update display fetching for coding in Encounter, Patient, and SexualOrientationObservation converters #1690

hub-prime/pom.xml, nexus-core-lib/pom.xml, nexus-core-lib/src/main/java/org/techbd/converters/csv/EncounterConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/OrganizationConverter.java, nexus-core-lib/src/main/java/org/techbd/converters/csv/PatientConverter.java, pom.xml
- New York state code change.
- Encounter type text value fix
=> fix: update state handling for New York in address processing for Encounter, Organization, and Patient converters #1690

support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt, support/specifications/develop/ccda/cda-fhir-bundle-medent.xslt, support/specifications/develop/ccda/cda-phi-filter-epic.xslt, support/specifications/develop/ccda/cda-phi-filter-medent.xslt
Added location resource to fhir bundle for Epic and Medent CCDA files
Added multiple answers for component question if present for both Epic and Medent CCD files
Updated cda-phi-filter xslt files to resolve issues when integrating to bridgelink.
=> feat: add location resource and multiple answers for component question to fhir bundle for Epic and Medent CCDA files #1714

support/specifications/develop/hl7/HL7V2 Bundle.xml
-  Initial commit of the BridgeLink channel for HL7V2 Bundle
- Changed channel’s inbound and outbound data types to Raw to handle HL7V2 messages directly
- Extracted and saved the original HL7V2 payload (ER7 format) into the database
- Updated source and destination transformer logic to support raw data flow
=> feat: BridgeLink HL7V2 Bundle channel implementation and raw payload handling #1695

support/specifications/develop/hl7/hl7v2-fhir-bundle.xslt
- Multiple answers handled for "96778-6"
- Handled Encounter Practitioner reference.
=> fix: handle multiple answer parameter and update status handling in HL7 transformation #1494

integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt, support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt, support/specifications/develop/ccda/cda-fhir-bundle-medent.xslt, support/specifications/develop/ccda/cda-fhir-bundle.xslt
Update xslt files to fix issue with participant element in encounter resource - removed the reference without a resource.
=> fix: update xslt files to fix issue with participant element in encounter resource #1714

support/specifications/develop/ccda/CcdaBundle.xml
- Added extractClinicalDocument(rawXml) to extract <ClinicalDocument> block from raw XML
- Handles optional XML declaration, BOM removal, and whitespace trimming
- Logs extracted content and handles errors gracefully
- Sets extracted XML to channelMap['fileContent']
#1709
=> feat: align v0.7.0 with Synthetic v0.4.28 by adding extractClinicalDocument #1709

support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json, support/specifications/flat-file/validate-nyher-fhir-ig-equivalent.py
- Updated validation patterns in the CSV specification for the following fields:
1. FAMILY_NAME
2. GIVEN_NAME
3. MIDDLE_NAME
- Improved error summary display:
Removed the file name from error messages shown during CSV field name mismatch
=> fix: update string validation patterns in CSV spec #1690

hub-prime/pom.xml, nexus-core-lib/pom.xml, nexus-ingestion-api/pom.xml, nexus-ingestion-api/src/main/java/org/techbd/ingest/controller/DataIngestionController.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/listener/MllpRoute.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/model/RequestContext.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/processor/SqsPublishStep.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/service/MessageGroupService.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/service/MetadataBuilderService.java, nexus-ingestion-api/src/test/java/org/techbd/ingest/processor/SqsPublishStepTest.java, nexus-ingestion-api/src/test/java/org/techbd/ingest/service/MessageGroupServiceTest.java, nexus-ingestion-api/src/test/java/org/techbd/ingest/service/MetadataBuilderServiceTest.java, pom.xml
- Added MessageGroupId field to the SQS message body.
-  Added additional logs to improve observability.
=> feat: add message group id to message json payload #1762

support/specifications/develop/ccda/TechBD CCD Workflow.xml
Updated CCDA Mirth Connect channel file
- resolves issue with file name allowing special characters to the name part while checking the allowed extensions.
- fixed the error while sending through httpyac without setting the value for the header variable, X-TechBD-Base-FHIR-URL. If it is not set, the value from the environment variable Base-FHIR-URL will be taken.
- done checking the valid file extensions before checking the existence of clinicaDocument tag in the input file
=> fix: update ccda mirth connect channel file to resolve issue with file name and header value not set.

nexus-ingestion-api/pom.xml, nexus-ingestion-api/src/main/java/org/techbd/ingest/config/MllpHealthIndicator.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/config/SecurityConfig.java, nexus-ingestion-api/src/main/java/org/techbd/ingest/controller/DataIngestionController.java
Implement health monitoring and robust security controls to improve reliability and compliance.
- Add Spring Boot Actuator dependency for production-ready health monitoring
- Implement MllpHealthIndicator to test MLLP service connectivity and availability
- Configure enterprise-grade security with principle of least privilege access control
#1761
=> feat: implement comprehensive health monitoring and security framework #1761

support/specifications/develop/ccda/CcdaBundle.xml
- Omit `class. Display` in Encounter resource if not present in input file.
- Omit `period.end` in Encounter resource if not present in input file.
=> fix(epic_AHC_Sample_CDA.xml): hide missing Encounter fields in payload #1709

hub-prime/src/main/resources/templates/page/interactions/httpscsv.html
-  Update the grid view description section and add  the visibility of the accordion content
=> fix: update the grid view description section and improve the visibility of accordion content. #1797

support/specifications/develop/hl7/ORU_R01.xml, support/specifications/develop/hl7/hl7v2-fhir-bundle.xslt
=> fix: update HL7 segment definitions and remove unnecessary checks in XSLT #1494

hub-prime/pom.xml, hub-prime/src/main/resources/templates/page/interactions/httpscsv.html, nexus-core-lib/pom.xml, pom.xml, support/specifications/flat-file/datapackage-nyher-fhir-ig-equivalent.json
- Update PATIENT_BIRTH_DATE pattern for strict YYYY-MM-DD format with valid month-day combinations and leap year support. #1690
=> fix: update PATIENT_BIRTH_DATE pattern for strict YYYY-MM-DD format with valid month-day combinations and leap year support. #1690

hub-prime/pom.xml, nexus-core-lib/pom.xml, nexus-ingestion-api/pom.xml, nexus-ingestion-api/src/main/java/org/techbd/ingest/endpoint/PnrEndpoint.java, pom.xml
- Use JAXBElement<T> for request/response parameters without @XmlRootElement
- Add ObjectFactory for proper SOAP response serialization
#1705
=> fix: resolve PNR endpoint JAXB mapping issue with JAXBElement wrappers #1705

integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt, support/specifications/develop/ccda/cda-fhir-bundle-medent.xslt
Resolved issue with category -> coding array in Observation Grouper Resource.
Removed 'serviceProvider' element from Encounter resource.
=> fix: resolve issue with category coding array #1825

support/specifications/develop/hl7/ORU_R01.xml, support/specifications/develop/hl7/hl7v2-fhir-bundle.xslt
- Changes for validation.
- Fix for CCDA-reported issue.
=> fix: remove unnecessary comments and adjust JSON structure #1494

integration-artifacts/ccda/ccda-techbd-channel-files/nexus/CcdaBundle.xml, integration-artifacts/version.json
- Fixed 'From State' column showing 'Validation Success' instead of 'Validation Failed' for invalid cases
- Ensured Original CCDA Payload nature is displayed for invalid cases
- Fixed tenant_id and tenant_id_lower columns showing as 'undefined' for invalid cases
#1709
=> feat: align v0.9.0 with Synthetic v0.4.29 for CCDA Bundle Endpoint #1709

integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt, integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-medent.xslt, integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle.xslt
Updated XSLT files for changing the category in observation resources for the question code '96782-8' to implement IG update 1.6.1
=> feat: move xslt files to aftifacts #1818

integration-artifacts/ccda/ccda-techbd-channel-files/nexus/CcdaBundle.xml, integration-artifacts/version.json
- Fixed issue where 'Converted to FHIR' nature was displayed when CCDA XML validation fails
- Ensured correct nature is preserved on validation failure
#1709
=> fix: align v0.11.0 with Synthetic v0.4.30 by correcting CCDA validation failure handling  #1709

integration-artifacts/hl7v2/hl7-techbd-channel-files/mirth-connect/TechBD HL7 Workflow.xml, integration-artifacts/hl7v2/hl7-techbd-schema-files/hl7v2-fhir-bundle.xslt, integration-artifacts/hl7v2/hl7-techbd-schema-files/hl7v2-validation-schema.xml
- Moved all relevant files from development to the integration folder for deployment.
=> refactor: moving files from develop to integration-artifacts #1494

nexus-core-lib/src/main/java/org/techbd/util/fhir/CoreFHIRUtil.java
- Updated CoreFHIRUtil.ensureEngineVersionMatches() to support resources loaded from local file system (file:) and packaged JARs (jar:).
- Local (file:) → validates directory exists and contains IG files.
- JAR (jar:) → checks resource existence using openStream().
- Prevents "URI is not hierarchical" errors when running in production.
- Added detailed logging for clarity on resolved paths and protocols.
=> fix: handle IG path resolution for both file and jar protocols #1791

hub-prime/src/main/java/org/techbd/service/http/Constant.java, hub-prime/src/main/java/org/techbd/service/http/FusionAuthUsersService.java, hub-prime/src/main/java/org/techbd/service/http/GitHubUserAuthorizationFilter.java, hub-prime/src/main/java/org/techbd/service/http/MultiProviderUserAuthorizationFilter.java, hub-prime/src/main/java/org/techbd/service/http/SecurityConfig.java, hub-prime/src/main/java/org/techbd/service/http/hub/prime/ux/Presentation.java, hub-prime/src/main/resources/application.yml, hub-prime/src/main/resources/templates/login/login.html, hub-prime/src/main/resources/templates/page/home.html
- Added Fusion auth basic login setup
- Removed Github login button from UI 
- #1687
=> feat: implement OAuth2 user authorization with FusionAuth support #1687

nexus-core-lib/src/main/java/org/techbd/service/fhir/engine/OrchestrationEngine.java
- Replaced inline Bundle parsing + validation with a call to `validateAsRawPayload(...)`
- Now validate using payload string instead of Bundle to enforce strict JSON structure
- Still parse payload as Bundle first with `fhirContext.newJsonParser().parseResource(Bundle.class, payload)` to ensure valid FHIR Bundle format
- Centralizes validation logic into reusable helper method
=> refactor: use validateAsRawPayload helper with payload string and Bundle parse (#1825)

nexus-core-lib/src/main/java/org/techbd/service/fhir/engine/OrchestrationEngine.java, pom.xml
- update version to 0.676.0
- close validateAsRawPayload method properly (#1825)
=> chore: update version to 0.676.0

hub-prime/src/main/java/org/techbd/service/http/SwaggerConfig.java, pom.xml
Ensure the `X-TechBD-Screening-Code` header/field is properly included in the Swagger documentation for the `/ccda/Bundle` endpoint.
=> fix(swagger): add X-TechBD-Screening-Code to /ccda/Bundle spec #1709

support/specifications/develop/ccda/cda-fhir-bundle-epic.xslt
Update xslt files to fix issue with encounter status in Epic CCDA files
=> fix: update xslt files to fix issue with encounter status in Epic CCDA files #1901

integration-artifacts/ccda/ccda-techbd-schema-files/cda-fhir-bundle-epic.xslt
Move changes of encounter status for Epic files to artifacts
=> fix: move changes of encounter status for Epic files to artifacts #1901

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CheckRoleController.java, hub-prime/src/main/java/org/techbd/service/http/FusionAuthUsersService.java, hub-prime/src/main/java/org/techbd/service/http/GitHubUserAuthorizationFilter.java, hub-prime/src/main/resources/templates/fragments/nav.html
- Added CheckRoleController and integrate DB role check in navigation for role rest test
=> feat: add CheckRoleController and integrate DB role check in navigation

hub-prime/src/main/java/org/techbd/controller/http/hub/prime/api/CheckRoleController.java
- Enhanced getCurrentDbRole method to include role setting and improved response handling
=> feat: enhance getCurrentDbRole method to include role setting and improved response handling

hub-prime/src/main/java/org/techbd/service/http/FusionAuthUsersService.java
- Updated hardcoded FusionAuth API token and tenant ID for consistency
=> fix: update hardcoded FusionAuth API token and tenant ID for consistency

hub-prime/src/main/resources/templates/page/content/hrsn-data-tracker.html, hub-prime/src/main/resources/templates/page/content/organizations.html, hub-prime/src/main/resources/templates/page/content/patients.html, hub-prime/src/main/resources/templates/page/content/screenings.html, hub-prime/src/main/resources/templates/page/diagnostics/data-integrity.html, hub-prime/src/main/resources/templates/page/diagnostics/fhir-validation-issues.html, hub-prime/src/main/resources/templates/page/diagnostics/file-not-processed.html, hub-prime/src/main/resources/templates/page/diagnostics/ig-publication-issues.html, hub-prime/src/main/resources/templates/page/diagnostics/incomplete-groups.html, hub-prime/src/main/resources/templates/page/diagnostics/needs-attention.html, hub-prime/src/main/resources/templates/page/diagnostics/qe-to-techbd.html, hub-prime/src/main/resources/templates/page/diagnostics/sftp-rejected.html, hub-prime/src/main/resources/templates/page/diagnostics/sftp.html, hub-prime/src/main/resources/templates/page/diagnostics/techbd-to-scoring-engine.html, hub-prime/src/main/resources/templates/page/interactions/https.html, hub-prime/src/main/resources/templates/page/interactions/httpsccda.html, hub-prime/src/main/resources/templates/page/interactions/httpscsv.html, hub-prime/src/main/resources/templates/page/interactions/httpsfailed.html, hub-prime/src/main/resources/templates/page/interactions/httpsfhir.html, hub-prime/src/main/resources/templates/page/interactions/httpshl7v2.html, hub-prime/src/main/resources/templates/page/interactions/observe.html, hub-prime/src/main/resources/templates/page/interactions/provenance.html, hub-prime/src/main/resources/templates/page/interactions/user.html
- Updated view names to include 'fusion_' prefix for consistency replacing the old view names
=> refactor: update view names to include 'fusion_' prefix for consistency

udi-prime/src/main/postgres/ingestion-center/update_fhir_and_file_counts_in_zip_interaction_table.md, udi-prime/src/main/postgres/ingestion-center/update_fhir_count.psql
Updated sql to fill the fhir bundle count in zip file request table
=> fix: update sql to fill the fhir bundle count #1912

support/specifications/develop/ccda/CcdaBundleValidate.xml
- Added interaction ID field to the response payload for CCDA Bundle validate endpoint.
=> feat: add interaction ID to response for CCDA Bundle validate endpoint #1709

pom.xml, support/specifications/develop/ccda/CcdaBundleValidate.xml
- Fixed the unknown IP address issue in CCDA bundle validation.
- Improved interaction ID handling for unhappy path responses.
- Bumped service version to 0.749.0.
=> fix: Resolve unknown IP in CCDA validation and improve interaction ID handling in unhappy path; bump to 0.749.0 #1709

integration-artifacts/ccda/ccda-techbd-channel-files/nexus/CcdaBundleValidate.xml, integration-artifacts/version.json
- Fixed the unknown IP address issue in CCDA bundle validation.
- Improved interaction ID handling for unhappy path responses.
- Updated `version.json` to reflect CCDA bundle validated version 0.11.0.
=> fix: Resolve unknown IP in CCDA validation and improve interaction ID handling in unhappy path #1709

udi-prime/src/main/postgres/ingestion-center/add_performance_indexes.psql
Drop unused views
- fhir_request 
- interaction_http_request_failed
=> refactor(db): remove unused database views #1912
